version: "2"
checks:
  similar-code:
    enabled: true
    config:
      languages:
      - javascript
      - typescript
  duplication:
    enabled: true
    config:
      languages:
      - javascript
      - typescript
exclude_patterns:
- node_modules/
- src/__test__/