version: "2"
checks:
  similar-code:
    enabled: true
    config:
      languages:
        typescript:
          count_threshold: 3
  # duplication:
  #   enabled: false
  #   config:
  #     languages:
  #     - javascript
  #     - typescript
exclude_patterns:
- node_modules/
- build/
- __test__/