version: "2"
checks:
  identical-code:
    enabled: false
    config:
      threshold:
  similar-code:
    enabled: false
    config:
      threshold:
exclude_patterns:
- node_modules/
- build/
- __test__/