version: "2"
# checks:
#   similar-code:
#     enabled: true
#     config:
#       languages:
#       - javascript
#       - typescript
#   duplication:
#     enabled: false
#     config:
#       languages:
#       - javascript
#       - typescript
exclude_patterns:
- node_modules/
- build/
- __test__/