FROM node:16-alpine

WORKDIR /usr/apps/express-typescript

COPY ./src .

COPY package*.json ./

# RUN yarn install --prod --frozen-lockfile && yarn run build
# RUN yarn install --production=true && yarn cache clean --all
RUN yarn install && yarn cache clean --all

CMD ["yarn", "watch"]